### ISSUE TITLE
Array.yank()

### ISSUE THREAD

**Issue by El-Dringo-Brannde** [El-Dringo-Brannde/Perfected-Prototypes#29]
A new function should appear on the prototype chain, similar to `arr.remove`, except the returned value is the values removed from the array. 

Example:
```javascript

const arr = [ 1,2,3,4]
const newArr = arr.yank(2)

console.log(newArr)
// => 2

const newNewArr = arr.yank([3,4])
console.log(newNewArr)
// => [3,4]

console.log(arr)
// => [1]
```

This should also update the README and the tests accordingly.

**Comment by decarbonite** [comment]
If the given parameter to yank is an array that contains values that exist in the main array and other values that is not in the main array, should it remove the ones that exist from the main array or just leave it as it is?
For example,
`var arr = [1,2,3,4,5]`  
 `arr.yank([5,6])`
what would  `console.log(arr)` output?

**Comment by El-Dringo-Brannde** [comment]
@decarbonite 
I think it should just remove the values in the given array that are present. 

So the `console.log` would look like.. 

``` javascript

var arr = [1,2,3,4,5]
arr.yank([5,6])

console.log(arr)
// -> [1,2,3,4]

```
